In [23]:
import numpy as np
from sklearn import svm, datasets
from sklearn.model_selection import cross_val_score, KFold
from sklearn.metrics import accuracy_score, f1_score

In [12]:
iris = datasets.load_iris()
X, y = iris.data, iris.target
clf = svm.SVC(probability=True, random_state=0)
cross_val_score(clf, X, y, scoring='neg_log_loss') 

array([-0.0757138 , -0.16816241, -0.07091847])

In [4]:
model = svm.SVC()
cross_val_score(model, X, y, scoring='accuracy')

array([ 0.98039216,  0.96078431,  0.97916667])

In [24]:

folds = 10
kf = KFold(n_splits=folds, shuffle=True, random_state=3245236)

accs = np.zeros(folds)

i = 0
for index_train, index_test in kf.split(X):
    model = svm.SVC()
    model.fit(X[index_train], y[index_train])
    
    y_true = y[index_test]
    y_pred = model.predict(X[index_test])
    
    accs[i] = f1_score(y_true, y_pred, average='micro')
    i = i + 1
    
print('mean ', np.mean(accs))
print('std ', np.std(accs))






mean  0.973333333333
std  0.0326598632371


In [9]:
model = svm.SVC()
cross_val_score(model, X, y, scoring='f1_macro')

array([ 0.98037518,  0.96064815,  0.9791463 ])